"""empty message

Revision ID: 69b0b93484cb
Revises: 77e83833755c
Create Date: 2023-09-22 09:23:01.977007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69b0b93484cb'
down_revision = '77e83833755c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_prompt_cases',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', postgresql.UUID(), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_prompt_cases_pkey')
    )
    with op.batch_alter_table('app_prompt_cases', schema=None) as batch_op:
        batch_op.create_index('app_id_idx', ['app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_prompt_cases', schema=None) as batch_op:
        batch_op.drop_index('app_id_idx')

    op.drop_table('app_prompt_cases')
    # ### end Alembic commands ###
